monolith:
  image: node:latest
  working_dir: /app
  volumes:
    - .:/app
  command: node /app/bin/www
  ports:
    - "3001:3000"
  links:
    - monolith2
  environment:
    - "test=value"

monolith2:
  image: node:latest
  working_dir: /app
  volumes:
    - .:/app
  command: node /app/bin/www
  ports:
    - "3002:3000"